CREATE OR REPLACE VIEW `{$project_id}.{$dataset_id}.base_coors_wr_kilometriert_excel_file` AS
SELECT
  t.ID,
  Land_von,
  Plz_von,
  Land_nach,
  Plz_nach,
  t.EventTimeStamp                                    AS eventTimestamp,
  ROUND(info.totalDistanceInMeters / 1000, 2)         AS GesamtDistanz,
  ROUND(info.totalStreetDistanceInMeters / 1000, 2)   AS StrasseDistanzGesamt,
  ROUND(info.totalTrainDistanceInMeters / 1000, 2)    AS BahnDistanzGesamt,
  ROUND(info.totalFerryDistanceInMeters / 1000, 2)    AS FaehreDistanzGesamt,
  ROUND(info.totalTravelTimeInSeconds / 60, 2)        AS Fahrzeit_Minuten,
  ROUND(info.totalTravelTimeInSeconds / 3600, 2)      AS Fahrzeit_Stunden,
  info.violated                                       AS Violated,
  rs.fromWaypoint.type                                AS from_type,
  rs.fromWaypoint.longitude                           AS from_longitude,
  rs.fromWaypoint.latitude                            AS from_latitude,
  rs.fromWaypoint.address.countryIsoCode              AS from_countryIsoCode,
  rs.fromWaypoint.address.postalCode                  AS from_postalCode,
  rs.toWaypoint.type                                  AS to_type,
  rs.toWaypoint.longitude                             AS to_longitude,
  rs.toWaypoint.latitude                              AS to_latitude,
  rs.toWaypoint.address.countryIsoCode                AS to_countryIsoCode,
  rs.toWaypoint.address.postalCode                    AS to_postalCode,
  vp.longitude                                        AS viapoint_longitude,
  vp.latitude                                         AS viapoint_latitude,
  vp.address.countryIsoCode                           AS viapoint_countryIsoCode,
  vp.address.city                                     AS viapoint_city,
  vp.address.postalCode                               AS viapoint_postalCode,
  rs.distanceInMeters / 1000                          AS distanceInMeters,
  rs.travelTimeInSeconds                              AS travelTimeInSeconds,
  rs.travelType                                       AS travelType,
  rs.walterRouteInfos.id                              AS walter_id,
  rs.walterRouteInfos.description                     AS walter_description,
  rs.walterRouteInfos.from.isoCountryCode             AS walter_from_isoCountryCode,
  rs.walterRouteInfos.from.postalCodes                AS walter_from_postalCodes,
  rs.walterRouteInfos.to.isoCountryCode               AS walter_to_isoCountryCode,
  rs.walterRouteInfos.to.postalCodes                  AS walter_to_postalCodes,
  rs.walterRouteInfos.isPreferred                     AS walter_isPreferred,
  rs.walterRouteInfos.prohibitedCountries             AS walter_prohibitedCountries,
  rs.walterRouteInfos.orgUnit                         AS walter_orgUnit,
  rs.segments                                         AS segments,
  tl.isoCountryCode                                   AS Toll_Iso_Country_Code,
  ROUND(tl.costInEuro, 2)                             AS Toll_Cost_Euro,
  ROUND(tl.distanceInMeters / 1000, 2)                AS Toll_Distance,
  tl.tollType                                         AS Toll_Type
FROM `{$project_id}.{$dataset_id}.base_coors_wr_kilometriert_current_view` AS t
LEFT JOIN UNNEST(t.routeSections)                     AS rs
LEFT JOIN UNNEST(rs.viapoints)                        AS vp
LEFT JOIN UNNEST(tolls)                               AS tl