CREATE OR REPLACE VIEW `{$project_id}.{$dataset_id}.base_coors_wr_kilometriert_excel_file` AS
SELECT
  t.ID,
  Land_von,
  Plz_von,
  Land_nach,
  Plz_nach,
  t.EventTimeStamp                                                      AS eventTimestamp,
  ROUND(info.totalDistanceInMeters / 1000, 2)                           AS GesamtDistanz,
  ROUND(info.totalStreetDistanceInMeters / 1000, 2)                     AS StrasseDistanzGesamt,
  ROUND(info.totalTrainDistanceInMeters / 1000, 2)                      AS BahnDistanzGesamt,
  ROUND(info.totalFerryDistanceInMeters / 1000, 2)                      AS FaehreDistanzGesamt,
  ROUND(info.totalTravelTimeInSeconds / 60, 2)                          AS Fahrzeit_Minuten,
  ROUND(info.totalTravelTimeInSeconds / 3600, 2)                        AS Fahrzeit_Stunden,
  info.violated                                                         AS Violated,
  JSON_VALUE(rs, '$.fromWaypoint.type')                                 AS from_type,
  CAST(JSON_VALUE(rs, '$.fromWaypoint.longitude') AS FLOAT64)           AS from_longitude,
  CAST(JSON_VALUE(rs, '$.fromWaypoint.latitude') AS FLOAT64)            AS from_latitude,
  JSON_VALUE(rs, '$.fromWaypoint.address.countryIsoCode')               AS from_countryIsoCode,
  JSON_VALUE(rs, '$.fromWaypoint.address.postalCode')                   AS from_postalCode,
  JSON_VALUE(rs, '$.toWaypoint.type')                                   AS to_type,
  CAST(JSON_VALUE(rs, '$.toWaypoint.longitude') AS FLOAT64)             AS to_longitude,
  CAST(JSON_VALUE(rs, '$.toWaypoint.latitude') AS FLOAT64)              AS to_latitude,
  JSON_VALUE(rs, '$.toWaypoint.address.countryIsoCode')                 AS to_countryIsoCode,
  JSON_VALUE(rs, '$.toWaypoint.address.postalCode')                     AS to_postalCode,
  CAST(JSON_VALUE(vp, '$.longitude') AS FLOAT64)                        AS viapoint_longitude,
  CAST(JSON_VALUE(vp, '$.latitude') AS FLOAT64)                         AS viapoint_latitude,
  JSON_VALUE(vp, '$.address.countryIsoCode')                            AS viapoint_countryIsoCode,
  JSON_VALUE(vp, '$.address.city')                                      AS viapoint_city,
  JSON_VALUE(vp, '$.address.postalCode')                                AS viapoint_postalCode,
  CAST(JSON_VALUE(rs, '$.distanceInMeters') AS FLOAT64) / 1000          AS distanceInMeters,
  CAST(JSON_VALUE(rs, '$.travelTimeInSeconds') AS FLOAT64)              AS travelTimeInSeconds,
  JSON_VALUE(rs, '$.travelType')                                        AS travelType,
  JSON_VALUE(rs, '$.walterRouteInfos.id')                               AS walter_id,
  JSON_VALUE(rs, '$.walterRouteInfos.description')                      AS walter_description,
  JSON_VALUE(rs, '$.walterRouteInfos.from.isoCountryCode')              AS walter_from_isoCountryCode,
  JSON_QUERY(rs, '$.walterRouteInfos.from.postalCodes')                 AS walter_from_postalCodes,
  JSON_VALUE(rs, '$.walterRouteInfos.to.isoCountryCode')                AS walter_to_isoCountryCode,
  JSON_QUERY(rs, '$.walterRouteInfos.to.postalCodes')                   AS walter_to_postalCodes,
  CAST(JSON_VALUE(rs, '$.walterRouteInfos.isPreferred') AS BOOL)        AS walter_isPreferred,
  JSON_QUERY(rs, '$.walterRouteInfos.prohibitedCountries')              AS walter_prohibitedCountries,
  JSON_VALUE(rs, '$.walterRouteInfos.orgUnit')                          AS walter_orgUnit,
  JSON_QUERY(rs, '$.segments')                                          AS segments,
  tl.isoCountryCode                                                     AS Toll_Iso_Country_Code,
  ROUND(tl.costInEuro, 2)                                               AS Toll_Cost_Euro,
  ROUND(tl.distanceInMeters / 1000, 2)                                  AS Toll_Distance,
  tl.tollType                                                           AS Toll_Type
FROM `{$project_id}.{$dataset_id}.base_coors_wr_kilometriert_current_view` AS t
LEFT JOIN UNNEST(JSON_QUERY_ARRAY(t.routeSections, '$'))                AS rs
LEFT JOIN UNNEST(JSON_QUERY_ARRAY(rs, '$.viapoints'))                   AS vp
LEFT JOIN UNNEST(tolls)                                                 AS tl